### ISSUE TITLE
Ending backslash in displayed user name breaks mention badge.

### ISSUE THREAD

**Issue by ZoomRmc** [vector-im/riot-web#4867]
### Description

Ending backslash in displayed user name breaks mention badge styling.

### Steps to reproduce

- Change the displayed user-name to something that ends with the backslash, e.g. ```user\```
- Mention such user
- Get ```[user](https://matrix.to/#/@user:matrix.org):``` displayed, instead of a styled badge

### Version information

- **Platform**: Web, Android
Checked in Firefox and Chrome.

- **Version**: Web: 0.12.1 Android: 0.7.00

**Comment by lukebarnard1** [comment]
Ah. We probably should escape user display names for inserting them into markdown.

**Comment by ZoomRmc** [comment]
Seems fixed in the web version.

**Comment by sandhose** [comment]
I have the same issue with someone that has a backtick in his username. The two backticks in the pill (once in the link, once in the text) are interpreted as an inline code block.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/1549952/29997728-51fb9ea2-901b-11e7-9802-632b7e664ab9.png">

Tested on develop and on stable.

**Comment by grahamperrin** [comment]
## `/develop/`

For an IRC user `[ade]` at <https://matrix.to/#/!GdmnfkDxuKZAICnOhe:matrix.org/$15055010117354830ilAZn:matrix.org>: 

![2017-09-15 19 44 01 riot 2](https://user-images.githubusercontent.com/192271/30498432-9e53904c-9a4e-11e7-819d-6e435c979cf2.png)

> Seems fixed in the web version.

Maybe not, or not for me. <https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$15054481726668574nPpFV:matrix.org> for screenshots of an earlier incident affecting an IRC user 

`Jan\`

**Comment by sbts** [comment]
Definitely still an issue for backticks in Nicks.
see #5135 for another example.
