### ISSUE TITLE
Make an option to hide calls related messages

### ISSUE THREAD

**Issue by J316** [vector-im/riot-web#6841]
It would be useful to have an option to hide automatic messages showing when a call starts or ends or a recipient answers

**Comment by 35609902357** [comment]
Any news on this?

**Comment by t3chguy** [comment]
Nope otherwise they'd be here. This is a very nice thing for contributors as it is simple.

**Comment by cheryllium** [comment]
I started a PR to add this option. I am not sure how to phrase it in the user interface, and the translator seems unable to process the text I chose. It shows up like this: 

```
missing translation: en-us|Show messages about call information
```

Would appreciate any advice on better phrasing, as well as understanding why the translator failed and how that can be prevented.

**Comment by t3chguy** [comment]
Run the i18n yarn script.

**Comment by cheryllium** [comment]
@t3chguy Thank you, I got it. Are there other scripts I need to run? It's failing e2e tests and I don't think my code should be affecting that part of the app.

**Comment by keremgocen** [comment]
hey @cheryllium do you need any help?

**Comment by SimonBrandner** [comment]
> hey @cheryllium do you need any help?

They have already made a [PR](https://github.com/matrix-org/matrix-react-sdk/pull/4387) which passed the code review. It's currently waiting for the product team to take a look

**Comment by robintown** [comment]
@J316 The way call events appear in the timeline has been reworked to display them as [event tiles](https://github.com/matrix-org/matrix-react-sdk/pull/6121), which automatically collapse together to save space and avoid showing a wall of call events. Do you feel this issue is solved now, or would you still like to be able to hide them?

**Comment by J316** [comment]
@robintown Yes, it's still an issue. Tiles actually make the situation worse especially on mobile.
