### ISSUE TITLE
Composer: Dead key modifiers don't work

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-web#7440]
We've seen a few reports of this, not identified as the same issue sooner due to my lack of familiarity with dead keys (sorry).

- https://github.com/vector-im/riot-web/issues/7124 - Dead keys stopped working in desktop
- https://github.com/vector-im/riot-web/issues/7149 - Making quotes or apostrophes with dead keys doesn't work
- https://github.com/vector-im/riot-web/issues/7191 - Superfluous space inserted after '
- https://github.com/vector-im/riot-web/issues/7439 - Typing single quote with keyboard config us_intl results in no single "'"
- https://github.com/vector-im/riot-web/issues/6862 (maybe) - Using BEPO keyboard layout inserting not breaking space moves the cursor to the start of the line

These might all be exactly the same bug - assembling here as a meta issue to track the problem generally.

**Comment by arthurlogilab** [comment]
thanks for compiling this !

**Comment by turt2live** [comment]
I'm curious as to how many of these would be fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2186

**Comment by turt2live** [comment]
@lampholder out of interest, how many of these magically got fixed by https://github.com/matrix-org/matrix-react-sdk/pull/2202

(*please say all of them... please say all of them...*)

**Comment by tulir** [comment]
Ubuntu 18.10 got these fancy input enhancements for dead keys and the compose key. Riot interferes with it a lot:

![riot-dead-keys](https://user-images.githubusercontent.com/4224639/47270266-27788d00-d572-11e8-982c-e5a5cf690722.gif)

**Comment by aperezdc** [comment]
Dead keys in stable (currently 0.17.2) with Spanish keyboard layout does not work at all. Spanish layout has dead keys for vowels with acute accents (`áéíóú`), which are used quite often, and for other less commonly used cases. I'll try to build `develop` and see how's the situation there.

**Comment by PureTryOut** [comment]
Please for the love of god give this some priority. I'm seriously copy and pasting in every ' I type in an English sentence now. This severely diminishes the user experience and I'm saddended to every time see a new release without a _potential_ fix.

**Comment by lampholder** [comment]
> @lampholder out of interest, how many of these magically got fixed by matrix-org/matrix-react-sdk#2202
>
> (please say all of them... please say all of them...)

I'm afraid it looks like none of them?

Sorry everyone that this is still a problem - it's _very_ high on the priority list and should get attention very soon :(

**Comment by turt2live** [comment]
> Dead keys in stable (currently 0.17.2) with Spanish keyboard layout does not work at all. Spanish layout has dead keys for vowels with acute accents (áéíóú), which are used quite often, and for other less commonly used cases. The issue is present in develop as well.

@aperezdc Which OS is this on? Also is it in a problem in Chrome, Firefox, a different browser, or Electron?

**Comment by turt2live** [comment]
> Ubuntu 18.10 got these fancy input enhancements for dead keys and the compose key. Riot interferes with it a lot:

@tulir I'm not able to reproduce this in an 18.10 VM with English US, the compose key enabled, and adding accents.

**Comment by aperezdc** [comment]
@turt2live This was on Arch Linux, happened both in X11 and Wayland sessions with any WebKitGTK+ based browser. In Electron, acute accents work (`áéíóú`) but other dead keys don't, and for example it's impossible to enter a backtick (which in Spanish layout is entered using the backtick dead key, then the space bar).

**Comment by turt2live** [comment]
So I've spent a few hours today trying to get Arch set up with no luck. Given the window manager can be whatever you want on Arch, I'm tempted to blame that as contributing to the bug. There is a bug in slate (upstream: https://github.com/vector-im/riot-web/issues/7441) that prevents some input methods from working, which I think might be the issue here. If you see if flickering or not appearing at all, that is consistent with that slate bug.

I've also managed to reproduce tulir's bug (finally) and can confirm it is a slate bug as well.

I'm closing this in favour of https://github.com/vector-im/riot-web/issues/7665 to track the upstream issue.

**Comment by aperezdc** [comment]
@turt2live I should have mentioned that the desktop environment I have been using is GNOME Shell. Some work mates who use GNOME on Debian have this issue as well. At any rate, thanks a lot for investigating! I'll subscribe to #7665 and to the upstream Slate issue to keep tabs on this.

**Comment by arthurlogilab** [comment]
I use the awesomewm window manager https://awesomewm.org/. Thanks for taking a look at this.

**Comment by Kabouik** [comment]
I'm having the same non-working dead keys issue in Solus Budgie, using us_intl keyboard.
