### ISSUE TITLE
Composer doesn't work with many input methods

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-web#7665]
Input methods (aka IMEs) from various operating systems and keyboard layouts cause problems with Riot. The symptoms include flashing characters, losing focus, misrepresentation of characters, etc. 

This is all tracked as an upstream issue: https://github.com/ianstormtaylor/slate/issues/2368

Here's what we have:
* https://github.com/vector-im/riot-web/issues/7441
* https://github.com/vector-im/riot-web/issues/7440
* https://github.com/vector-im/riot-web/issues/7124
* https://github.com/vector-im/riot-web/issues/7419
* https://github.com/vector-im/riot-web/issues/7218
* https://github.com/vector-im/riot-web/issues/7155
* https://github.com/vector-im/riot-web/issues/7639
* https://github.com/vector-im/riot-web/issues/7488
* https://github.com/vector-im/riot-web/issues/5495
* https://github.com/vector-im/riot-web/issues/6101
* https://github.com/vector-im/riot-web/issues/7482
* https://github.com/vector-im/riot-web/issues/7535
* https://github.com/vector-im/riot-web/issues/8114

**Comment by turt2live** [comment]
I think I got all of them. Please point out any issues I might have missed.

**Comment by mvgorcum** [comment]
you missed #7149

**Comment by turt2live** [comment]
#7149 is a duplicate of another issue on this list.

**Comment by mathiasblc** [comment]
Just so you know that I'm now experiencing the same characters problem with macOS 10.14.1, Safari 12.0.1 & the US Intl keymap. Very annoying indeed.

![out](https://user-images.githubusercontent.com/41020854/48434577-59989b80-e77a-11e8-94f5-935fef67426a.gif)

**Comment by ninjin** [comment]
I can confirm this issue on NixOS, Firefox, and Fcitx with Mozc for Japanese input. Whatever I type is stochastically swallowed and I would sadly say that things are unusable at this point, if I want to type in Japanese I will have to type it in another window and paste it into the Riot web client.

**Comment by palytoxin** [comment]
I have the same problem on macos.

**Comment by kiliankoe** [comment]
I'm not sure about the progress that was made here, but I've noticed that typing umlauts is now possible. A new issue however is that I'm often unable to use backspace, or sometimes type at all, unless I restart Riot. The app doesn't freeze up or anything like that, some forms of input just no longer work in the message field.

**Comment by kiliankoe** [comment]
![text](https://user-images.githubusercontent.com/2625584/54210902-9a40c100-449d-11e9-9dc7-301dee6c842c.gif)

I have to restart/reload Riot several times daily when it gets itself into a weird state regarding text input 😕 Often this happens after typing German umlauts, suddenly I can't use backspace, or typing doesn't work at all, or text just reappears after deleting it (as shown in the gif). This feels extremely broken.

I feel the message input is doing way too much *magic*, whatever it's trying to achieve with that. It should just be a text field that works.

**Comment by kiliankoe** [comment]
Sorry for piling ever more comments onto this issue, but I've noticed that I've been invoking <kbd>cmd</kbd><kbd>a</kbd> + <kbd>backspace</kbd> twice, since it always fails the first time 😕

**Comment by aaronraimist** [comment]
Someone should try to update to the latest version of Slate. The upstream issue isn't fixed but people keep reporting that it is better on the latest versions.

**Comment by longfan3** [comment]
@aaronraimist @turt2live When i try to update the Slate to 0.44.12, I got the error : 
```As of Slate 0.42.0, value object are no longer schema-aware, and the `value.change()` method is no longer available. Use the `editor.change()` method on the new `Editor` controller instead.```
Do you have a related upgrade plan?

**Comment by avoidr** [comment]
I didn't want to open yet another issue, but just wanna ping that input doesn't work beyond the keys input directly with keypress on the keyboard. I can't input Korean and Chinese via ibus, and X compose key doesn't work either.

**Comment by ara4n** [comment]
let the record show that we're solving this by moving away from Slate to a lightweight editor we wrote ourselves called [CIDER](https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/ciderEditor.md).  Please help us test it by going to riot.im/develop and turning on the new editor in Labs in Settings, and hopefully almost all of these issues are resolved.

**Comment by xuhdev** [comment]
@ara4n I went to riot.im/develop but the issue still persists...

**Comment by jryans** [comment]
> @ara4n I went to riot.im/develop but the issue still persists...

Sorry to be pedantic, but did you also go to Settings -> Labs, enable the new composer, and reload Riot? (The new composer is not enabled by default yet.)

**Comment by xuhdev** [comment]
@jryans That works! Thanks!

**Comment by avoidr** [comment]
Works! Gonna take a while to beat my input-phobia now :D

**Comment by rixtox** [comment]
Here is a normal input sequence:
![](https://giant.gfycat.com/IdleSlipperyArmyworm.gif)

But the behavior in CIDER is:
![](https://giant.gfycat.com/ObeseGleefulEnglishpointer.gif)

**Comment by cetex** [comment]
> let the record show that we're solving this by moving away from Slate to a lightweight editor we wrote ourselves called [CIDER](https://github.com/matrix-org/matrix-react-sdk/blob/develop/docs/ciderEditor.md). Please help us test it by going to riot.im/develop and turning on the new editor in Labs in Settings, and hopefully almost all of these issues are resolved.

Sweet!

The new one seems to work much better from ~2minutes of testing, now i can even paste stuff into the riot.im message-field on linux/wayland (sway) without having to open webinspector -> elements -> event listeners -> remove listener on paste, paste my stuff, post, then reload riot.im to make it work for normal messaging again..

**Comment by bwindels** [comment]
Thanks @rixtox, have split this out into a separate issue: https://github.com/vector-im/riot-web/issues/10913

**Comment by turt2live** [comment]
🎉 🎉 🎉  fixed  🎉 🎉 🎉
